/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Layout from "@/components/layout";
import { Input } from "@nextui-org/react";
import Image from "next/image";
import Pengumuman from "../../public/pengumuman.svg";
import Panduan from "../../public/panduan.svg";
import Mobile from "../../public/mobile.svg";
import Head from "next/head";
import { useRouter } from "next/router";
export default function Index() {
  const route = useRouter();
  return (
    <Layout>
      <Head>
        <title>Sisfo-Feb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="shadow-xl px-10 py-5 bg-fixed bg-[url('https://sisfo.upiyptk.ac.id/images/bgweb.png')]">
        <main className="">
          <div className="flex flex-col lg:flex-row-reverse  justify-between">
            <div className="flex-col justify-center items-center">
              <div className="bg-yellow-300 bg-opacity-50 shadow-2xl p-11 rounded-xl border-2 flex flex-col justify-center items-center">
                <div className="rounded-full overflow-clip w-24 aspect-square">
                  <img
                    className="hover:scale-105 duration-500 "
                    src="https://scontent-sin6-3.xx.fbcdn.net/v/t39.30808-6/318955127_1619120191880844_6036713440562724685_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=M6z91y3naXEAX_U3Kx2&_nc_ht=scontent-sin6-3.xx&oh=00_AfCihcjpPu_IHaFvsmj-u50fo5MotGu972M2IH3ZzwVwAQ&oe=63CC0483"
                    alt="#"
                  />
                </div>
                <h1 className="text-center  text-2xl font-bold text-[#62372E] mt-4">
                  Febriqgal Purnama
                </h1>
                <h1 className="text-center mb-5 text-xl font-medium text-[#62372E] ">
                  19101152610060
                </h1>
                <h1 className="text-center text-lg font-bold text-[#62372E]">
                  Sistem Informasi akademi
                </h1>

                <button
                  onClick={() => {
                    route.push("/");
                  }}
                  className="border border-[#62372E] my-5 hover:text-white hover:bg-[#62372E] rounded-lg px-4 py-2"
                >
                  Keluar
                </button>
                <div className="flex gap-2 text-sm">
                  <Image src={Panduan} alt="#" />
                  <h1 className="  text-[#62372E]">Panduan Sisfo</h1>
                  <Image src={Mobile} alt="#" />
                  <h1 className="  text-[#62372E]">Mobile Apps</h1>
                </div>
              </div>
            </div>
            <div>
              <div className="flex items-start mt-10 gap-5 ">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="fill-red-900 bg-yellow-400 shadow-xl p-5 rounded-full filter"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Informasi Perkuliahan
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Diinformasikan kepada mahasiswa Universitas Putra Indonesia
                    YPTK Padang, Perkuliahan Tanggal : 26 Desember s.d 31
                    Desember 2022 ditiadakan. Lihat Pengumuman :
                    <span className=" font-bold text-[#EE4C0C]"> view »</span>
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Penyusunan Kartu Rencana Studi (KRS) Sistem Kombinasi
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Diberitahukan Kepada Mahasiswa UPI-YPTK Padang Penyusunan
                    Kartu Rencana Studi (KRS) Sistem Kombinasi Dapat Disusun
                    Pada : Tanggal : 28 November s.d 23 Desember 2022
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">PENGUMUMAN</h1>
                  <h1 className="lg:w-[500px] text-justify">
                    {`
                    Di informasikan kepada Mahasiswa Universitas Putra Indonesia
                    "YPTK" Padang, Perkuliahan Tanggal 18 s.d 20 Oktober 2022
                    ditiadakan, baik Online ataupun Offline kuliah kembali
                    sebagaimana mestinya tanggal : 21 Oktober 2022 dan mengikuti
                    jadwal yang ada pada situs resmi Sisfo Kampus UPI-YPTK
                    Padang.
                   `}
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Pembekalan Pendidikan Karakter (PPK)
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    {`Sehubungan dengan akan dilaksanakannya Pembekalan Pendidikan Karakter (PPK) bagi mahasiswa Angkatan 2021 dan 2022 di lingkungan Universitas Putra Indonesia "YPTK" Padang secara offline (tatap muka) pada tanggal 26-29 September 2022, bersama ini disampaikan beberapa hal kepada Mahasiswa Angkatan 2021 dan Angkatan 2022 sebagai berikut :  download »`}
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Pengumuman Kalender Akademik
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Kalender Akademik terbaru sudah bisa dilihat Disini »
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    PUBLIKASI TUGAS AKHIR (TA) MAHASISWA DI JURNAL
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Dalam rangka menghasilkan lulusan Perguruan Tinggi yang
                    memenuhi Standar Nasional Pendidikan Tinggi (SNPT) sesuai
                    dengan PERMEN DIKTI No. 49 Tahun 2014, PERMENRISTEK DIKTI
                    No. 44 Tahun 2015, PERMENRISTEKDIKTI No. 50 Tahun 2018 dan
                    Surat Edaran DIRJEN BELMAWA RISTEK DIKTI No.
                    B/323/B.B1/SE/2019 tentang Publikasi Karya Ilmiah. Download
                    Surat Edaran Disini »
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Penyusunan Kartu Rencana Studi (KRS) Online
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Diberitahukan Kepada Mahasiswa UPI-YPTK Padang Penyusunan
                    Kartu Rencana Studi (KRS) Online Dapat Disusun Pada : Hari /
                    Tgl : Senin - 14 September s.d Sabtu - 19 September 2020,
                    Bagi yang telah PA-Online KRS Wajib Di Cetak dan dibawa Pada
                    Saat Perkuliahan Semester Ganjil Tahun Akademik 2020/2021,
                    Download Pedoman PA Online »
                  </h1>
                </div>
              </div>
              <div className="flex items-start mt-10 gap-5">
                <Image
                  width={80}
                  src={Pengumuman}
                  alt={"#"}
                  className="bg-yellow-400 shadow-xl p-5 rounded-full"
                />
                <div>
                  <h1 className="font-bold text-[#62372E]">
                    Template Jurnal Skripsi Mahasiswa
                  </h1>
                  <h1 className="lg:w-[500px] text-justify">
                    Bagi Mahasiswa yang Skripsi silahkan Download Template
                    Jurnal untuk Skripsi Mahasiswa Program Sarjana pada link
                    dibawah ini : Download Template Jurnal
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </main>
        <footer className="text-center mt-5 ">© 2023 - Febriqgal😎</footer>
      </div>
    </Layout>
  );
}
