/* eslint-disable @next/next/no-img-element */
import React from "react";
import Image from "next/image";
import Panduan from "../../public/panduan.svg";
import Mobile from "../../public/mobile.svg";
import Styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import Head from "next/head";
import { Button, Input } from "@nextui-org/react";
export default function Home() {
  const route = useRouter();
  return (
    <>
      <Head>
        <title>Login | Sisfo-Feb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div
        className={`${Styles.main} bg-fixed bg-[url('https://sisfo.upiyptk.ac.id/images/bgweb.png')]`}
      >
        <div className="flex-col justify-center">
          <div className="bg-yellow-300 bg-opacity-50 shadow-2xl p-11 rounded-xl border-2 flex flex-col justify-center items-center">
            <h1 className="text-center  text-2xl font-bold text-[#62372E] mt-4">
              Login
            </h1>
            <Input className="mb-2 mt-8" placeholder="No. BP" />
            <Input type={"password"} placeholder="Password" />
            <Button
              onClick={() => {
                route.push("/home");
              }}
              className="mt-8 w-full hover:-translate-y-1"
              value={"ddd"}
              width={500}
              color={"warning"}
            >
              Login
            </Button>
            <div className="flex gap-2 text-sm mt-8">
              <Image src={Panduan} alt="#" />
              <h1 className="  text-[#62372E]">Panduan Sisfo</h1>
              <Image src={Mobile} alt="#" />
              <h1 className="  text-[#62372E]">Mobile Apps</h1>
            </div>
          </div>
        </div>
        <h1 className="absolute bottom-5">© 2023 - Febriqgal😎</h1>
      </div>
    </>
  );
}
