import Layout from "@/components/layout";
import React from "react";
import Styles from "../styles/Home.module.css";
import Head from "next/head";
export default function perkuliahan() {
  const TitlePage = "Tugas Akhir";
  return (
    <Layout>
      <Head>
        <title>{TitlePage} | Sisfo-Feb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={Styles.main}>
        <h1>{`${TitlePage} (Coming Soon!!!)`}</h1>
      </main>
    </Layout>
  );
}
